networks:
  default_heat_demand_profiles_net:

volumes:
  influxdb_data:

services:
  influxdb:
    image: influxdb:1.7
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_RETENTION_ENABLED=false
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - ./influxdb/1.init.iql:/docker-entrypoint-initdb.d/1.init.iql
      - ./influxdb/2.upload_data.sh:/docker-entrypoint-initdb.d/2.upload_data.sh
      - ./influxdb/energy_profiles.warmingup_default_profiles.influx_line:/energy_profiles.warmingup_default_profiles.influx_line
      - influxdb_data:/var/lib/influxdb
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/ping" ]
      interval: 10s
      timeout: 5s
    networks:
      default_heat_demand_profiles_net:

  caddy:
    image: caddy
    restart: unless-stopped
    environment:
      - PROTOCOL=${PROTOCOL}
      - INFLUX_DOMAIN=${INFLUX_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    networks:
      default_heat_demand_profiles_net:
        aliases:
          - ${INFLUX_DOMAIN}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - influxdb
